# Generated by Django 3.2 on 2021-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_identifier', models.CharField(default='', max_length=80, unique=True)),
                ('price', models.CharField(max_length=12, null=True)),
                ('date_of_transfer', models.CharField(max_length=30, null=True)),
                ('postal_code', models.CharField(max_length=12, null=True)),
                ('property_type', models.CharField(max_length=2, null=True)),
                ('old_new', models.CharField(max_length=2, null=True)),
                ('duration', models.CharField(max_length=2, null=True)),
                ('paon', models.CharField(max_length=100, null=True)),
                ('saon', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('district', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('ppd_cat', models.CharField(max_length=100, null=True)),
                ('record_stat', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
